spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springtest
    username: springuser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

jwt:
  header: Authorization
  secret: spring-security-test
  expiration: 604800

auth:
  signin: /auth/signin
  signup: /auth/signup
  refresh: /auth/refresh